# Generated by Django 4.1.4 on 2023-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=50)),
            ],
        ),
    ]
